### ISSUE TITLE
Legacy password login not working in HA 0.84.1

### ISSUE THREAD

**Issue by thagoat** [estevez-dev/ha_client#247]
1213 14:12:09 [Debug] :  <!!!> Creating new HomeAssistant instance
1213 14:12:09 [Debug] :  AppLifecycleState.inactive
1213 14:12:09 [Debug] :  AppLifecycleState.resumed
1213 14:12:09 [Debug] :  Use lovelace is true
1213 14:12:09 [Debug] :  Socket connecting...
1213 14:12:09 [Error] :  Invalid argument(s): 56.0
1213 14:12:09 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
1213 14:12:09 [Error] :  NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
1213 14:12:09 [Debug] :  [Sending] ==> auth request
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
1213 14:12:09 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
1213 14:12:09 [Debug] :  [Received] <== id:1, error
1213 14:12:09 [Debug] :  [Received] <== id:2, error
1213 14:12:09 [Debug] :  [Received] <== id:4, success
1213 14:12:09 [Debug] :  [Received] <== id:6, error
1213 14:12:09 [Warning] :  There was an error getting current user: {id: 6, type: result, success: false, error: {code: no_user, message: Not authenticated as a user}}
1213 14:12:09 [Debug] :  [Received] <== id:3, error
1213 14:12:09 [Error] :  There was an error getting Lovelace config: {id: 3, type: result, success: false, error: {code: config_not_found, message: No config found.}}
1213 14:12:09 [Debug] :  [Received] <== id:5, success
1213 14:12:15 [Debug] :  Settings changed. Saving...
1213 14:12:15 [Debug] :  Settings change event: reconnect=true
1213 14:12:15 [Debug] :  Use lovelace is false
1213 14:12:15 [Debug] :  Socket connecting...
1213 14:12:15 [Debug] :  [Sending] ==> auth request
1213 14:12:15 [Debug] :  [Sending] ==> {"id": 7, "type": "subscribe_events", "event_type": "state_changed"}
1213 14:12:15 [Debug] :  [Sending] ==> {"id": 8, "type": "get_states"}
1213 14:12:15 [Debug] :  [Sending] ==> {"id": 9, "type": "get_config"}
1213 14:12:15 [Debug] :  [Sending] ==> {"id": 10, "type": "get_services"}
1213 14:12:15 [Debug] :  [Sending] ==> {"id": 11, "type": "auth/current_user"}
1213 14:12:15 [Debug] :  [Received] <== id:7, error
1213 14:12:15 [Debug] :  [Received] <== id:8, error
1213 14:12:15 [Debug] :  [Received] <== id:9, success
1213 14:12:15 [Debug] :  [Received] <== id:11, error
1213 14:12:15 [Warning] :  There was an error getting current user: {id: 11, type: result, success: false, error: {code: no_user, message: Not authenticated as a user}}
1213 14:12:15 [Debug] :  [Received] <== id:10, success
1213 14:12:16 [Debug] :  Use lovelace is false
1213 14:12:16 [Debug] :  [Sending] ==> {"id": 12, "type": "get_states"}
1213 14:12:16 [Debug] :  [Sending] ==> {"id": 13, "type": "get_config"}
1213 14:12:16 [Debug] :  [Sending] ==> {"id": 14, "type": "get_services"}
1213 14:12:16 [Debug] :  [Sending] ==> {"id": 15, "type": "auth/current_user"}
1213 14:12:16 [Debug] :  [Received] <== id:12, error
1213 14:12:16 [Debug] :  [Received] <== id:13, success
1213 14:12:16 [Debug] :  [Received] <== id:14, success
1213 14:12:16 [Debug] :  [Received] <== id:15, error
1213 14:12:16 [Warning] :  There was an error getting current user: {id: 15, type: result, success: false, error: {code: no_user, message: Not authenticated as a user}}

**Comment by estevez-dev** [comment]
"No config found" it means that there is no lovelace ui configured on your HA. Is it works when "use lovelace UI" is off in settings?

**Comment by thagoat** [comment]
No it doesn't work either way, on or off. ui-lovelace.yaml is in my .homeassistant directory

**Comment by estevez-dev** [comment]
You are using legacy password to login? If yes, you need to switch to access token: https://www.vynn.co/ha-client/documentation/#config-auth

**Comment by thagoat** [comment]
Ah, ok I'll give that a whirl, thanks!

**Comment by estevez-dev** [comment]
API login with legacy password will not work any more, starting from HA 0.84.0.
